# Generated by Django 3.0.3 on 2021-03-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('vehicle_class', models.CharField(choices=[('Light', 'Light'), ('Bicycle', 'Bicycle'), ('Bus', 'Bus'), ('ArticulatedTruck', 'ArticulatedTruck'), ('SingleUnitTruck', 'SingleUnitTruck')], max_length=20)),
                ('entrance', models.CharField(choices=[('E', 'East'), ('W', 'West'), ('N', 'North'), ('S', 'South')], max_length=1)),
                ('exit', models.CharField(choices=[('E', 'East'), ('W', 'West'), ('N', 'North'), ('S', 'South')], max_length=1)),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
    ]
